//USER TYPES

export const SET_CURRENT_USER = "SET_CURRENT_USER";

//CATEGORY TYPES

export const SET_CATEGORIES = "SET_CATEGORIES";

//CART TYPES
export const SET_IS_CART_OPEN = "SET_IS_CART_OPEN";
export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const SET_CART_COUNT = "SET_CART_COUNT";
export const SET_CART_TOTAL = "SET_CART_TOTAL";
